index:
    path: /
    controller: App\Controller\MainController::indexAction

acerca_de:
    path: /acerca-de
    controller: App\Controller\MainController::aboutAction

proyectos:
    path: /proyectos
    controller: App\Controller\MainController::proyectosAction

sitemap:
    path: /sitemap
    controller: App\Controller\MainController::sitemapAction
